// Generated by delombok at Fri Jun 12 22:06:31 IST 2026
package com.mmagym.bot.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "class_feedback")
public class ClassFeedback {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;
    @Column(nullable = false)
    private LocalDate classDate;
    @Column(length = 50)
    private String classType;
    @Column(nullable = false, columnDefinition = "TINYINT")
    private int rating; // 1=Tough, 2=Good, 3=Easy
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Member getMember() {
        return this.member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getClassDate() {
        return this.classDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getClassType() {
        return this.classType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMember(final Member member) {
        this.member = member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClassDate(final LocalDate classDate) {
        this.classDate = classDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClassType(final String classType) {
        this.classType = classType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRating(final int rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
