// Generated by delombok at Fri Jun 12 22:06:31 IST 2026
package com.mmagym.bot.model;

import jakarta.persistence.*;
import java.time.LocalTime;

@Entity
@Table(name = "gym_classes")
public class GymClass {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, length = 100)
    private String className;
    @Column(nullable = false)
    private int dayOfWeek; // ISO weekday: 1=Monday … 7=Sunday
    @Column(nullable = false)
    private LocalTime classTime;
    @Column(nullable = false)
    private LocalTime classEndTime;
    @Column(nullable = false)
    private int maxCapacity = 20;
    @Column(length = 100)
    private String coach;
    @Column(nullable = false)
    private boolean isActive = true;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getClassName() {
        return this.className;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getDayOfWeek() {
        return this.dayOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getClassTime() {
        return this.classTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalTime getClassEndTime() {
        return this.classEndTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getMaxCapacity() {
        return this.maxCapacity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCoach() {
        return this.coach;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isActive() {
        return this.isActive;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClassName(final String className) {
        this.className = className;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDayOfWeek(final int dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClassTime(final LocalTime classTime) {
        this.classTime = classTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setClassEndTime(final LocalTime classEndTime) {
        this.classEndTime = classEndTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaxCapacity(final int maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCoach(final String coach) {
        this.coach = coach;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActive(final boolean isActive) {
        this.isActive = isActive;
    }
}
