// Generated by delombok at Fri Jun 12 22:06:31 IST 2026
package com.mmagym.bot.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "members")
public class Member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false, length = 100)
    private String name;
    @Column(nullable = false, unique = true, length = 20)
    private String phone;
    private LocalDate dob;
    @Column(precision = 5, scale = 2)
    private BigDecimal weightKg;
    @Column(nullable = false)
    private int streakCount = 0;
    @Column(nullable = false)
    private boolean streakShield = false;
    private LocalDate lastCheckinDate;
    private LocalDate lastNudgeDate;
    private LocalDate joinDate;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PlanType planType;
    private LocalDate planExpiry;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus paymentStatus = PaymentStatus.UNPAID;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MemberStatus status = MemberStatus.ACTIVE;
    @Column(length = 200)
    private String emergencyContact;
    @Column(columnDefinition = "TEXT")
    private String injuries;
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;


    public enum PlanType {
        MONTHLY, QUARTERLY, ANNUAL;

        public LocalDate calculateExpiry(LocalDate from) {
            return switch (this) {
                case MONTHLY -> from.plusMonths(1);
                case QUARTERLY -> from.plusMonths(3);
                case ANNUAL -> from.plusYears(1);
            };
        }
    }


    public enum PaymentStatus {
        PAID, UNPAID, EXPIRED;
    }


    public enum MemberStatus {
        ACTIVE, INACTIVE, SUSPENDED;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDob() {
        return this.dob;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWeightKg() {
        return this.weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getStreakCount() {
        return this.streakCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isStreakShield() {
        return this.streakShield;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getLastCheckinDate() {
        return this.lastCheckinDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getLastNudgeDate() {
        return this.lastNudgeDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getJoinDate() {
        return this.joinDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PlanType getPlanType() {
        return this.planType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getPlanExpiry() {
        return this.planExpiry;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MemberStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmergencyContact() {
        return this.emergencyContact;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getInjuries() {
        return this.injuries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDob(final LocalDate dob) {
        this.dob = dob;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeightKg(final BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStreakCount(final int streakCount) {
        this.streakCount = streakCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStreakShield(final boolean streakShield) {
        this.streakShield = streakShield;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastCheckinDate(final LocalDate lastCheckinDate) {
        this.lastCheckinDate = lastCheckinDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastNudgeDate(final LocalDate lastNudgeDate) {
        this.lastNudgeDate = lastNudgeDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setJoinDate(final LocalDate joinDate) {
        this.joinDate = joinDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlanType(final PlanType planType) {
        this.planType = planType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlanExpiry(final LocalDate planExpiry) {
        this.planExpiry = planExpiry;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPaymentStatus(final PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final MemberStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmergencyContact(final String emergencyContact) {
        this.emergencyContact = emergencyContact;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setInjuries(final String injuries) {
        this.injuries = injuries;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
