// Generated by delombok at Fri Jun 12 22:06:31 IST 2026
package com.mmagym.bot.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "milestone_awards", uniqueConstraints = @UniqueConstraint(name = "uq_member_milestone", columnNames = {"member_id", "milestone"}))
public class MilestoneAward {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;
    @Column(nullable = false)
    private int milestone;
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime awardedAt;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Member getMember() {
        return this.member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getMilestone() {
        return this.milestone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getAwardedAt() {
        return this.awardedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMember(final Member member) {
        this.member = member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMilestone(final int milestone) {
        this.milestone = milestone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAwardedAt(final LocalDateTime awardedAt) {
        this.awardedAt = awardedAt;
    }
}
