// Generated by delombok at Fri Jun 12 22:06:31 IST 2026
package com.mmagym.bot.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name = "progress")
public class Progress {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;
    @Column(nullable = false)
    private LocalDate logDate;
    @Column(precision = 5, scale = 2)
    private BigDecimal weightKg;
    @Column(length = 50)
    private String metricType;
    @Column(precision = 8, scale = 2)
    private BigDecimal value;
    @Column(columnDefinition = "TEXT")
    private String notes;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Member getMember() {
        return this.member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getLogDate() {
        return this.logDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getWeightKg() {
        return this.weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMetricType() {
        return this.metricType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getValue() {
        return this.value;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMember(final Member member) {
        this.member = member;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogDate(final LocalDate logDate) {
        this.logDate = logDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeightKg(final BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMetricType(final String metricType) {
        this.metricType = metricType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setValue(final BigDecimal value) {
        this.value = value;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }
}
